### ISSUE TITLE
Repo createContents error

### ISSUE THREAD

**Issue by MisteFr** [pksunkara/octonode#319]
Hey,

I am actually using this library to post some files on github.
I am posting 4 files in a row and the fourth time I am getting this error ``Repo createContents error``but sometimes the file is correctly uploaded and sometimes not.

It might be because you can put two files in the same time (the two operations are executed almost at the same time) ?

Traceback:
```
Error: Repo createContents error
    at /home/MisteBot/node_modules/octonode/lib/octonode/repo.js:554:21
    at Client.errorHandle (/home/MisteBot/node_modules/octonode/lib/octonode/client.js:249:14)
    at Request._callback (/home/MisteBot/node_modules/octonode/lib/octonode/client.js:363:24)
    at Request.self.callback (/home/MisteBot/node_modules/request/request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/home/MisteBot/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (/home/MisteBot/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by MisteFr** [comment]
All is working perfectly if I post the second file once the first was posted (using the callback of the first createContents).
I am going to close this issue as I think that's it's not an issue on your side but more on github side.
