### ISSUE TITLE
Github auth login - Not Found

### ISSUE THREAD

**Issue by NotroDev** [pksunkara/octonode#359]
Heeey, I'm using octonode and I need auth to get the rate limit higher. I try this code ...
var github = require('octonode');
var gitClient = github.client();

var scopes = {
  'scopes': ['user', 'repo', 'gist'],
  'note': 'admin script'
};

github.auth.config({
  username: 'NotroDev',
  password: process.env.GIT_PASS
}).login(scopes, function (err, id, token, headers) {
    console.log(err);
    //console.log(id, token);
});

...but i am getting this error:
`Error: Not Found
    at Request._callback (/home/runner/SkEditorBot/node_modules/octonode/lib/octonode/auth.js:90:31)
    at Request.self.callback (/home/runner/SkEditorBot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Request.<anonymous> (/home/runner/SkEditorBot/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at IncomingMessage.<anonymous> (/home/runner/SkEditorBot/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)`

process.env.GIT_PASS is my password.

Sorry, I'm probably doing it completely wrong, I don't know much about such things.

**Comment by pksunkara** [comment]
They removed that endpoint recently. You can not use the password based authentication anymore.

**Comment by NotroDev** [comment]
> They removed that endpoint recently. You can not use the password based authentication anymore.

how can i auth then?
